apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dev-sa-cluster-admin
subjects:
  - kind: ServiceAccount
    name: dev-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: dev
  labels:
    app: dev
spec:
  serviceAccountName: dev-sa
  restartPolicy: Never
  containers:
    - name: workspace
      image: dev:latest
      imagePullPolicy: Never # To use local image that Kind uploaded, preventing image pull from docker.io
      command: ["sleep", "infinity"] # keep the pod alive
      volumeMounts:
        - mountPath: /workspace
          name: src
  volumes:
    - name: src
      hostPath:
        path: /workspace
        type: Directory
