apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: pushsecret-example
  namespace: default
spec:
  updatePolicy: Replace
  deletionPolicy: Delete
  refreshInterval: 10s
  secretStoreRefs:
    - name: target-cluster
      kind: SecretStore
  selector:
    secret:
      name: my-secret
  data:
    - match:
        secretKey: username
        remoteRef:
          remoteKey: my-secret-copy
          property: username-copy
    - match:
        secretKey: password
        remoteRef:
          remoteKey: my-secret-copy
          property: password-copy
