apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: target-cluster
  namespace: default
spec:
  provider:
    kubernetes:
      remoteNamespace: default
      server:
        url: https://k3d-target-cluster-server-0:6443
        caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTXpFMU5qUTNOakV3SGhjTk1qUXhNVEUwTURZeE1qUXhXaGNOTXpReE1URXlNRFl4TWpReApXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTXpFMU5qUTNOakV3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFRS3JRMG1La3FmejF0Q1QyWFdRcTZqNUdhVXdNd2YvRy8wMnBQdTQzTngKcTJwY1NZY0ozQ1lwLzNaM0hETVdrMmVDTUZVYmxDUklUREI3VE1kQnlMZHdvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVU91VGxKTGJZTDlQY3VYQzEwY2pDCkEwM3d1d1F3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQUxKbFptNWloSG9iZnZvNGUrVExYeGNtYWZNWEtvcU8KYXE3NzV1cTI0WDhyQWlBVnYyZjVJQW5PUUhubUJsUkFMZ3RmL0E5M05QbHNxOG1aQmVvQlF1NEcydz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      auth:
        cert:
          clientCert:
            name: target-cluster-credentials
            key: client-certificate-data
          clientKey:
            name: target-cluster-credentials
            key: client-key-data
