apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: private-chart
spec:
  clusterSelector: {} # すべてのクラスターにデプロイ
  repoURL: oci://ghcr.io/suin
  chartName: hello-world  # あなたのチャート名
  version: "0.1.0"      # あなたのチャートのバージョン
  releaseName: hello-world
  namespace: hello-world-system
  credentials:
    secret:
      name: github-creds
      namespace: caaph-system
    key: config.json
  options:
    waitForJobs: true
    atomic: true
    wait: true
    timeout: 5m
    install:
      createNamespace: true
