apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: foo
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        namespace: default
      data:
        key1: value1
        key2: value2
  providerConfigRef:
    name: kubernetes-provider
