apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: demo02-config-map
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        namespace: default
      data:
        hello: world
