apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: some-web-app
  namespace: default
spec:
  image: ghcr.io/$GITHUB_ORG_NAME/some-web-app
  interval: 5m
  secretRef:
    name: github-registry-pull-secret
