apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xtexts.demo07.suin.jp
spec:
  group: demo07.suin.jp
  names:
    kind: XText
    plural: xtexts
  versions:
    - name: v1
      referenceable: true
      served: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                value:
                  type: string
              required:
                - value
