apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: demo-create-config-map-with-kcl
spec:
  compositeTypeRef:
    apiVersion: platform.suin.jp/v1
    kind: XDemo08
  mode: Pipeline
  pipeline:
    - step: create-config-map
      functionRef:
        name: function-kcl
      input:
        apiVersion: krm.kcl.dev/v1alpha1
        kind: KCLInput
        spec:
          source: |
            configMap = {
              apiVersion = "kubernetes.crossplane.io/v1alpha2"
              kind = "Object"
              metadata = {
                annotations = {
                  "krm.kcl.dev/composition-resource-name" = "demo08-configmap"
                }
              }
              spec = {
                forProvider = {
                  manifest = {
                    apiVersion = "v1"
                    kind = "ConfigMap"
                    metadata = {
                      namespace = "default"
                    }
                    data = {
                      key1 = "value1"
                      key2 = "value2"
                    }
                  }
                }
                providerConfigRef = {
                  name = "kubernetes-provider"
                }
              }
            }
            items = [configMap]
    - step: automatically-detect-ready-composed-resources
      functionRef:
        name: function-auto-ready
