apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: pushsecret-example
  namespace: default
spec:
  updatePolicy: Replace
  deletionPolicy: Delete
  refreshInterval: 10s
  secretStoreRefs:
    - name: aws-secretsmanager
      kind: SecretStore
  selector:
    secret:
      name: my-secret
  data:
    - match:
        secretKey: foo
        remoteRef:
          remoteKey: my-secret-foo
      metadata:
        secretPushFormat: string
