apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: podinfo
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: podinfo
  progressDeadlineSeconds: 60
  service:
    port: 9898
    targetPort: 9898
    # No hosts field
    gatewayRefs:
      - name: eg
        namespace: ($namespace)
  analysis:
    interval: 1s
    threshold: 5
    maxWeight: 50
    stepWeight: 10
