kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  ipFamily: dual
nodes:
  - role: control-plane
    image: kindest/node:v1.33.1
    extraMounts:
      # Mounts the Docker socket so that the Cluster API Docker provider (CAPD) can access the host Docker.
      - hostPath: /var/run/docker.sock
        containerPath: /var/run/docker.sock
      # 
      - hostPath: ./certs.d
        containerPath: /etc/containerd/certs.d
# Tells containerd to pull images for docker.io and registry.k8s.io from Google’s mirror.gcr.io first.
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry]
      config_path = "/etc/containerd/certs.d"
    # Enable debug mode to check if mirror.gcr.io is used.
    # The log can be seen by running `docker exec -it <cluster-name>-control-plane bash -c 'journalctl -u containerd -f & crictl pull nginx'`
    [debug]
      level = "debug"
