apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: demo06-to-configmap
spec:
  compositeTypeRef:
    apiVersion: demo06.suin.jp/v1alpha1
    kind: XConfigMap
  resources:
    - name: configmap
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha2
        kind: Object
        spec:
          forProvider:
            manifest:
              apiVersion: v1
              kind: ConfigMap
              metadata:
                namespace: default
      patches:
        - fromFieldPath: metadata.name
          toFieldPath: metadata.name
        - fromFieldPath: spec.data
          toFieldPath: spec.forProvider.manifest.data
