apiVersion: v1
entries:
  hello-world:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2024-11-21T14:33:43.264939+09:00"
    description: A simple Helm chart that creates hello-world namespace
    digest: aa98a225f32f7d140aeb7ebff38ccb42ec31924b3a4e10bb8cc01da1c567b79b
    name: hello-world
    type: application
    urls:
    - hello-world-0.1.0.tgz
    version: 0.1.0
generated: "2024-11-21T14:33:43.26471+09:00"
