apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: shirts.stable.example.com
spec:
  group: stable.example.com
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              color:
                type: string
              size:
                type: string
              price:
                type: integer
            required:
            - color
            - size
          status:
            type: object
            properties:
              available:
                type: boolean
    # This is the key feature - declaring selectable fields
    selectableFields:
    - jsonPath: .spec.color
    - jsonPath: .spec.size
    - jsonPath: .spec.price
    additionalPrinterColumns:
    - jsonPath: .spec.color
      name: Color
      type: string
    - jsonPath: .spec.size
      name: Size
      type: string
    - jsonPath: .spec.price
      name: Price
      type: integer
  scope: Namespaced
  names:
    plural: shirts
    singular: shirt
    kind: Shirt 