apiVersion: repo.github.upbound.io/v1alpha1
kind: Repository
metadata:
  name: repo2
spec:
  forProvider:
    name: test-repo-2
    visibility: private
    description: Repository created by Crossplane using the GitHub Provider with GitHub App.
  providerConfigRef:
    name: github-provider-github-app
