# This rule is not used by the project pseudo-cluster-scope-key itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to pseudo-cluster-scope-key.example.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: pseudo-cluster-scope-key
    app.kubernetes.io/managed-by: kustomize
  name: dog-viewer-role
rules:
- apiGroups:
  - pseudo-cluster-scope-key.example.com
  resources:
  - dogs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pseudo-cluster-scope-key.example.com
  resources:
  - dogs/status
  verbs:
  - get
