# This rule is not used by the project pseudo-cluster-scope-key itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over pseudo-cluster-scope-key.example.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: pseudo-cluster-scope-key
    app.kubernetes.io/managed-by: kustomize
  name: dog-admin-role
rules:
- apiGroups:
  - pseudo-cluster-scope-key.example.com
  resources:
  - dogs
  verbs:
  - '*'
- apiGroups:
  - pseudo-cluster-scope-key.example.com
  resources:
  - dogs/status
  verbs:
  - get
