# This rule is not used by the project pseudo-cluster-scope-key itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the pseudo-cluster-scope-key.example.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: pseudo-cluster-scope-key
    app.kubernetes.io/managed-by: kustomize
  name: dog-editor-role
rules:
- apiGroups:
  - pseudo-cluster-scope-key.example.com
  resources:
  - dogs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pseudo-cluster-scope-key.example.com
  resources:
  - dogs/status
  verbs:
  - get
