---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - pseudo-cluster-scope-key.example.com
  resources:
  - dogs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pseudo-cluster-scope-key.example.com
  resources:
  - dogs/finalizers
  verbs:
  - update
- apiGroups:
  - pseudo-cluster-scope-key.example.com
  resources:
  - dogs/status
  verbs:
  - get
  - patch
  - update
