---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: default
spec:
  encryptedData:
    password: AgDhen26BK+/6BNw9ynqCsigMDf0ekeSCOnEnKnXrvfWg9Z5fUPm1A9x0RhYAOpIRlPrZe+9WOfDgAtfVfBfXsnyMiB8+l41tfFt9ZUMOHRTn/Mf/XrHj8CykUb+xUO5g7xYmCCiYDZ8w7VzYrLs/nWAa705RXAadLdjPk9wwTZ+zdPO+L2mOXX3CUrEViiCHTGhTe2QlnPXIDfn1AQ0zfuuHXsaEIAK2I9WJPvnITtCyVq5sRg3QttTeEPFDPWng9VRSKSt0pwaRuhuzV/EI2w7BppBEi/lBeIoJaSIllDtfWl2/e167+7hqXq3Ww0eMQ5Kl+EwTrhJeghWFi85e19O1PfjAQaqX4Vm2X/JIy76QV2pQEJdLmT0oncL1BIO6yLlE9//QWkiUKXDZprg63DPJ9nAzZkqmbAcgHLlVFQl8jKxcAv/4sWv1iKDzAobYaN04WxmQHVYkA9ThETe2eWHkCfVSWFk6XqFM2hRz8ifkLe7JSIrfKvFM+ojkn+pTy0tZIZC1A9mwksedEeXGUyuCmE8P5e7LeiCk3qSZVVSzZFGAMfn9vKV+9raPDezkTuqB4Wqn51vjIa573xr6WwgDejKH+mt7CVFJIID1jb8t3Rlqtq0EwsKsyEScUKzXPfZKohjcwzyXpIoq+K2cEyMME3dymkgX6Uk46e6MizEc2RXLSLtfMYkiJ21xV+qM+UNIljFKRCXY31J
    username: AgBsO0p89uKM3duG3Qm0/CtxRiZ5iXgvIHYNShaX3ycIvyF+ZlsUlZ5VJVIpCh0KP+4hIHV+78JzOegTG5nTt30kv18BRI1/VItCNmTdiwxlHOBGxbrsT1YkfDWxU+K1ePCdYp483TzDs6yt3qBV8p9eUk28S/ABz6mA+tO2AnxAFtkEOTBv0pVWutqm7gR6ygb0Ys4H4FVn47se5NkIfPt3aPXqAZ2CxayGBJiv+znvT4ZmDhssJ+0lsb/j2kPPrb0BCXjbaiX1bWWu4/etnLpr+0phL6WHSc1b/smf6q3reSFKm4II9WNfrIRuw8WN6085IlLfpY2TYA7cFnuAueFyZ155o5mjgp2VKKskK54wn3XJjBz4lXhBQkVLA5oUqJHjk7dgc01bUbTwiTpXQsYwTx3UESsZUXpugFdlPoblwHw2ioep9hPsBU/GYgnvQ/NnfR9dZI6hFQzY67RL6TK+/ChlHoUcgAiuZ69K+MTmPeJo7OYsncDc+Inv9dsDm1Tu188Il9X/JpxL+CWMXZ4BfTsl0YgHFJikAlU6SS++XoJxX9vbvnPSV3GZnB0JiZYZTXi4/5898fuTnz8Dsom+egt/wF8PZwontIZtViSGdooFfdbeSolfurxxqa/8E7Ut5B9DwdZPV3y+2Khux35BmhG4LO1a0XVhF8p9Dbu8w+5YreSEYEeJr3jKicIAhkx6csjLlQ==
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: default
    type: Opaque
